import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@modules/providers";
import CommonClient from "./CommonClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "bg-white text-base text-neutral-900 dark:bg-neutral-900 dark:text-neutral-200"
        )}
      >
        <Providers>
          <main className="relative">
            {children}
            <CommonClient />
          </main>
        </Providers>
      </body>
    </html>
  );
}
